services:
  app:
    image: value-calculator:latest
    container_name: value-calculator-app
    ports:
      - "8080:8080"
    env_file:
      - .env

    volumes:
      - ./application.yml:/app/config/application.yml:ro
    environment:
      SPRING_CONFIG_ADDITIONAL_LOCATION: /app/config/

    restart: unless-stopped

networks:
  value-calculator-network:
    driver: bridge
