spring:
  application:
    name: value-calculator

  datasource:
      url: jdbc:mysql://value-calculator-db.cj8yo000ag6t.ap-northeast-2.rds.amazonaws.com:3306/value_calculator?useSSL=true&serverTimezone=Asia/Seoul
      username: ${DB_USERNAME:admin}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

# ??? ??? ??
kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  auth-url: https://kauth.kakao.com
  api-url: https://kapi.kakao.com

# JWT ??
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.unit_wiseb.value_calculator: DEBUG

server:
  port: 8080

